POST https://httpbin.org/post
Content-Type: application/json

{
  "id": "{{$guid}}",
  "name": "Edy Segura",
  "description": "This is just a test payload!",
  "createdAt": "{{$timestamp}}"
}

###

GET https://httpbin.org/uuid