POST /rest/v5.3/parser/personnameparser?apiKey={{$dotenv NAME_API_KEY}}
Host: api.nameapi.org
Content-Type: application/json

{
  "inputPerson": {
    "type": "NaturalInputPerson",
    "personName": {
      "nameFields": [
        {
          "string": "Renê Martins",
          "fieldType": "FULLNAME"
        }
      ]
    }
  }
}
