GET https://nominatim.openstreetmap.org/search.php?q=santa%20rita%20do%20sapuca%C3%AD&polygon_geojson=1&countrycodes=br&format=jsonv2

###

GET https://nominatim.openstreetmap.org/reverse?format=json&lat=-22.2486968&lon=-45.7064507

