GET https://nominatim.openstreetmap.org/search.php?city=Pouso Alegre&state=MG&country=Brazil&format=jsonv2

###

GET https://nominatim.openstreetmap.org/search.php?city=Santa Rita do Sapucaí&state=MG&country=Brazil&format=jsonv2

###

GET https://nominatim.openstreetmap.org/reverse?format=json&lat=-22.2343858&lon=-45.9327241

###

GET https://nominatim.openstreetmap.org/reverse?format=json&lat=-22.2486968&lon=-45.7064507