### Variables
@baseUrl = https://pokeapi.co/api/v2/pokemon

# @name pokeResponse
GET {{baseUrl}}
    ?offset=0
    &limit=3

###

GET {{pokeResponse.response.body.$.next}}

###

GET {{pokeResponse.response.body.$.results[1].url}}