### Variables
@baseUrl = https://pokeapi.co/api/v2/pokemon

# @name pokeResponse
GET {{baseUrl}}
    ?offset=0
    &limit=3

###

GET {{baseUrl}}/{{pokeResponse.response.body.$.results[1].name}}

###

GET {{pokeResponse.response.body.$.next}}
