@baseUrl = https://viacep.com.br/ws

GET {{baseUrl}}/37558140/json/

###

GET {{baseUrl}}/37550199/json/

###

GET {{baseUrl}}/37537144/json/

###

GET {{baseUrl}}/37537208/json/

###

GET {{baseUrl}}/37537138/json/