GET https://viacep.com.br/ws/37558140/json/

###

GET https://viacep.com.br/ws/37550199/json/

###

GET https://viacep.com.br/ws/37537144/json/

###

GET https://viacep.com.br/ws/37537208/json/

###

GET https://viacep.com.br/ws/37537138/json/